variable "ibmcloud_api_key" {
  type        = string
  description = "The IBM Cloud API token this account authenticates to"
  sensitive   = true
}

variable "ibmcloud_secret_store_api_key" {
  type        = string
  description = "The IBM Cloud API token when the private key secrets manager is in a different account"
  sensitive   = true
  default     = null
}

variable "prefix" {
  type        = string
  description = "Prefix for sm instance"
  default     = "secrets-manager-test"
}

variable "region" {
  type        = string
  description = "Region where resources will be created"
  default     = "us-east"
}

variable "resource_group" {
  type        = string
  description = "An existing resource group name to use for this example, if unset a new resource group will be created"
  default     = null
}

variable "cis_id" {
  type        = string
  description = "Cloud Internet Service ID"
}

variable "resource_tags" {
  type        = list(string)
  description = "Optional list of tags to be added to created resources"
  default     = []
}

variable "ca_name" {
  type        = string
  description = "Secret Managers certificate authority name"
  default     = "certificate-auth"
}

variable "acme_letsencrypt_private_key" {
  type        = string
  description = "The private key generated by the ACME account creation tool. Required if private_key_secrets_manager_instance_guid and private_key_secrets_manager_secret_id are not set."
  sensitive   = true
  default     = null
}

variable "dns_provider_name" {
  type        = string
  description = "Name of the DNS provider for the public_cert secrets engine"
  default     = "certificate-dns"
}

variable "cert_common_name" {
  type        = string
  description = "Certificate common name, is the domain name to be secured by the certificate"
  default     = null
}

variable "private_key_secrets_manager_instance_guid" {
  type        = string
  description = "The Secrets Manager instance GUID of the Secrets Manager containing your ACME private key. Required if acme_letsencrypt_private_key is not set."
  default     = null
}

variable "private_key_secrets_manager_secret_id" {
  type        = string
  description = "The secret ID of your ACME private key. Required if acme_letsencrypt_private_key is not set. If both are set, this value will be used as the private key."
  default     = null
}

variable "private_key_secrets_manager_region" {
  type        = string
  description = "The region of the Secrets Manager instance containing your ACME private key. (Only needed if different from the region variable)"
  default     = null
}
