variable "ibmcloud_api_key" {
  type        = string
  description = "The IBM Cloud API key used to provision resources."
  sensitive   = true
}

variable "existing_secrets_manager_crn" {
  type        = string
  description = "CRN of an existing secrets manager instance to create the secret engine in."
}

variable "prefix" {
  type        = string
  description = "The prefix to be added to all resources created by this solution. To skip using a prefix, set this value to null or an empty string. The prefix must begin with a lowercase letter and may contain only lowercase letters, digits, and hyphens '-'. It should not exceed 16 characters, must not end with a hyphen('-'), and can not contain consecutive hyphens ('--'). Example: prod-us-south."

  validation {
    condition = (var.prefix == null ? true :
      alltrue([
        can(regex("^[a-z]{0,1}[-a-z0-9]{0,14}[a-z0-9]{0,1}$", var.prefix)),
        length(regexall("^.*--.*", var.prefix)) == 0
      ])
    )
    error_message = "Prefix must begin with a lowercase letter, contain only lowercase letters, numbers, and '-' characters. It must end with a lowercase letter or number, and be 16 or fewer characters long."
  }

  validation {
    # must not exceed 16 characters in length
    condition     = length(var.prefix) <= 16
    error_message = "Prefix must not exceed 16 characters."
  }
}

variable "ibmcloud_cis_api_key" {
  type        = string
  description = "An API key for CIS DNS configuration which is to be used when not using IAM authorization."
  default     = null
  sensitive   = true
}

variable "internet_services_crn" {
  type        = string
  description = "The CRN of the CIS instance to authorize Secrets Manager against."
  default     = null
}

variable "cis_account_id" {
  type        = string
  description = "The Account ID of the CIS instance (only needed if different from Secrets Manager account)"
  default     = null
}

variable "internet_service_domain_id" {
  type        = string
  description = "Specific domain in the CIS to authorize Secrets Manager access to."
  default     = null
}

variable "dns_config_name" {
  type        = string
  description = "Name of the DNS config for the public_cert secrets engine. If a prefix input variable is specified, it is added to the value in the `<prefix>-value` format."
  default     = "certificate-dns"
}

variable "ca_config_name" {
  type        = string
  description = "Name of the CA config for the public_cert secrets engine. If a prefix input variable is specified, it is added to the value in the `<prefix>-value` format."
  default     = "cert-auth"
}

variable "lets_encrypt_environment" {
  type        = string
  description = "Let's Encrtyp environment (staging, production)"
  default     = "production"
}

variable "acme_letsencrypt_private_key" {
  type        = string
  description = "The private key generated by the ACME account creation tool. Required if private_key_secrets_manager_instance_guid and private_key_secrets_manager_secret_id are not set."
  default     = null
  sensitive   = true
}

variable "skip_iam_authorization_policy" {
  type        = bool
  description = "Set to true to skip the creation of an IAM authorization policy that permits Secrets Manager to create a DNS config in the CIS specified in `internet_services_crn`. WARNING: An authorization policy must exist before a DNS config can be created, OR an API key must be provided in `ibmcloud_cis_api_key`"
  default     = false
}

variable "private_key_secrets_manager_instance_guid" {
  type        = string
  description = "The Secrets Manager instance GUID of the Secrets Manager containing your ACME private key. Required if acme_letsencrypt_private_key is not set."
  default     = null
}

variable "private_key_secrets_manager_secret_id" {
  type        = string
  description = "The secret ID of your ACME private key. Required if acme_letsencrypt_private_key is not set. If both are set, this value will be used as the private key."
  default     = null
}

variable "private_key_secrets_manager_region" {
  type        = string
  description = "The region of the Secrets Manager instance containing your ACME private key. (Only needed if different from the region variable)."
  default     = null
}
